# Sponsors - TheCee Project

github: sahajpatel123
# Add other platforms if applicable:
# - patreon
# - ko_fi
# - opensourcefunding
# - issuehunt
# - ko_fi
# - liberapay
# - ovirt
# - buy_me_a_coffee
# - kofi

custom: https://buy.me/thecee