#!/usr/bin/env python3
"""Generate hash-pinned lock files from pip dry-run reports.

Scorecard's PinnedDependencies probe treats any ``pip install`` with a
non-flag argument as unpinned — even ``pkg==version``. The only accepted
shapes are ``--require-hashes``, ``*.whl``, or pinned editable installs,
so CI installs must go through fully hash-locked requirements files.

Pipeline:
  1. ``pip install --dry-run --only-binary :all: --report r.json <specs>``
     resolves the exact transitive closure under the CI interpreter
     (python 3.11, pip 25.2).
  2. This script reads the report and asks PyPI's JSON API for EVERY
     distribution file of each pinned version (wheels for all platforms +
     sdist), emitting ``name==version --hash=sha256:...`` lines.

Including every platform's hashes is what makes one lock file usable on
both ubuntu x86_64 CI runners and arm macOS dev machines.

Usage:
    python tools/gen_dependency_lock.py report.json output.lock "title"
"""

from __future__ import annotations

import json
import sys
import time
from urllib.error import URLError
from urllib.request import urlopen

PYPI_JSON = "https://pypi.org/pypi/{name}/{version}/json"


def fetch_all_hashes(name: str, version: str, attempts: int = 4) -> list[tuple[str, str]]:
    """Return (filename, sha256) for every file published for this release.

    Retries transient TLS/connection failures — a 72-package run spans
    minutes and one handshake blip should not abort it.
    """
    url = PYPI_JSON.format(name=name, version=version)
    last_exc: Exception | None = None
    for attempt in range(attempts):
        try:
            with urlopen(url, timeout=30) as resp:  # noqa: S310 - fixed https host
                data = json.load(resp)
            break
        except (URLError, TimeoutError, OSError) as exc:
            last_exc = exc
            time.sleep(2 * (attempt + 1))
    else:
        raise RuntimeError(f"PyPI metadata unavailable after {attempts} tries: {url}") from last_exc
    out = []
    for f in data.get("urls", []):
        digest = f.get("digests", {}).get("sha256")
        if digest:
            out.append((f["filename"], digest))
    return out


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__)
        return 2
    report_path, out_path, title = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(report_path) as fh:
        report = json.load(fh)

    pins = sorted(
        ((p["metadata"]["name"], p["metadata"]["version"]) for p in report["install"]),
        key=lambda t: t[0].lower(),
    )

    lines = [
        f"# {title}",
        "# Generated by tools/gen_dependency_lock.py from a pip --dry-run",
        "# resolution under python 3.11 / pip 25.2; hashes cover every",
        "# distribution file PyPI publishes for each pinned version.",
        "# Regenerate: see the header of tools/gen_dependency_lock.py.",
        "# Install only with --require-hashes:",
        f"#   pip install --no-cache-dir --require-hashes -r {out_path.rsplit('/', 1)[-1]}",
        "",
    ]
    missing: list[str] = []
    for name, version in pins:
        files = fetch_all_hashes(name, version)
        if not files:
            missing.append(f"{name}=={version}")
            continue
        # pip's requirements parser only treats a line as a continuation
        # when the previous line ends with a backslash — indentation alone
        # is not enough. Comments can't follow the backslash, so hash lines
        # carry no annotations (same shape pip-compile emits).
        lines.append(f"{name}=={version} \\")
        for index, (_, digest) in enumerate(sorted(files)):
            cont = " \\" if index < len(files) - 1 else ""
            lines.append(f"    --hash=sha256:{digest}{cont}")

    with open(out_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"{out_path}: {len(pins)} packages")
    if missing:
        print("MISSING FILES:", ", ".join(missing))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
